In [2]:
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

from sklearn import preprocessing
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#importing the dataset
dataset = pd.read_csv('C:/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

#taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN',strategy="mean",axis=0)
imputer.fit(X[:,[1,2]])
X[:,[1,2]] = imputer.transform(X[:,[1,2]])

#encoding the categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelEncoder_X = LabelEncoder()
X[:,0]=labelEncoder_X.fit_transform(X[:,0])

onehotEncoder  = OneHotEncoder(categorical_features=[0])
X = onehotEncoder.fit_transform(X).toarray()


#label encoding to the y treain dataset
labelEncoding_y = LabelEncoder()
y= labelEncoding_y.fit_transform(y)


#splittting the dattaset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33)


#applying feature scaling to the x-train and y_train data
from sklearn.preprocessing import StandardScaler
standard_scalar = StandardScaler()
standard_scalar.fit(X_train)
X_train = standard_scalar.transform(X_train)

In [3]:
print(X_train)

[[-0.70710678 -0.4472136   1.         -0.02109803 -0.07872224]
 [ 1.41421356 -0.4472136  -1.         -0.18385424  0.51444067]
 [-0.70710678 -0.4472136   1.          0.10549014 -0.96846659]
 [-0.70710678 -0.4472136   1.         -1.81141637 -1.36390853]
 [ 1.41421356 -0.4472136  -1.          1.6064641   1.70076648]
 [-0.70710678  2.23606798 -1.          0.3044144   0.19589022]]


In [5]:
print(y_train)

[0 1 0 1 1 1]
